# Generated by Django 5.0 on 2026-01-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_attachment_message_is_voice_message_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
