# Generated by Django 6.0.1 on 2026-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quiz_quizquestion_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
